# Use official Nginx image as a base
FROM nginx:stable-alpine

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the frontend static files
COPY frontend/public /usr/share/nginx/html/public

# Copy the frontend template files (HTML files)
COPY frontend/templates /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]